[project]
name = "math-ppt-plan-reason-mcp-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.2.5",
    "google-genai>=1.12.1",
    "mcp>=1.6.0",
    "numpy>=2.2.5",
    "pillow>=11.2.1",
    "python-dotenv>=1.1.0",
    "python-pptx>=1.0.2",
]
